# -*- coding: utf-8 -*-
"""Itule

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oZc6oOYdB6CSw2w-gFn6dQVKUcG_CPzF

# Regression

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

"""## Importing the dataset"""

dataset = pd.read_csv('Wellbeing_and_lifestyle_.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values
#y = y.reshape(len(y),1)

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)

"""## Training the SVR model on the whole dataset"""

from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X, y)

"""## Determining accuracy
 
"""
y_pred = regressor.predict(X_test)
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

#t=[[5,4,0,2,10,10,5,1,2,7,4,1,5,8,5,2,2,1,8,4,'36 to 50',1]]

#t=ct.transform(t)
#regressor.predict(t)
import pickle
pickle.dump(regressor, open('model.pkl','wb'))
model = pickle.load(open('model.pkl','rb'))